// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v3.21.12
// source: msg.proto

package pb

import (
	pb "github.com/libp2p/go-libp2p-record/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// MessageType represents the type of RPC being called. Based on the message
// type different fields of this message will be populated. The response
// of a message with a certain type will have the same type.
type Message_MessageType int32

const (
	Message_PUT_VALUE     Message_MessageType = 0
	Message_GET_VALUE     Message_MessageType = 1
	Message_ADD_PROVIDER  Message_MessageType = 2
	Message_GET_PROVIDERS Message_MessageType = 3
	Message_FIND_NODE     Message_MessageType = 4
	Message_PING          Message_MessageType = 5
)

// Enum value maps for Message_MessageType.
var (
	Message_MessageType_name = map[int32]string{
		0: "PUT_VALUE",
		1: "GET_VALUE",
		2: "ADD_PROVIDER",
		3: "GET_PROVIDERS",
		4: "FIND_NODE",
		5: "PING",
	}
	Message_MessageType_value = map[string]int32{
		"PUT_VALUE":     0,
		"GET_VALUE":     1,
		"ADD_PROVIDER":  2,
		"GET_PROVIDERS": 3,
		"FIND_NODE":     4,
		"PING":          5,
	}
)

func (x Message_MessageType) Enum() *Message_MessageType {
	p := new(Message_MessageType)
	*p = x
	return p
}

func (x Message_MessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_MessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[0].Descriptor()
}

func (Message_MessageType) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[0]
}

func (x Message_MessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_MessageType.Descriptor instead.
func (Message_MessageType) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0, 0}
}

type Message_ConnectionType int32

const (
	// sender does not have a connection to peer, and no extra information (default)
	Message_NOT_CONNECTED Message_ConnectionType = 0
	// sender has a live connection to peer
	Message_CONNECTED Message_ConnectionType = 1
	// sender recently connected to peer
	Message_CAN_CONNECT Message_ConnectionType = 2
	// sender recently tried to connect to peer repeatedly but failed to connect
	// ("try" here is loose, but this should signal "made strong effort, failed")
	Message_CANNOT_CONNECT Message_ConnectionType = 3
)

// Enum value maps for Message_ConnectionType.
var (
	Message_ConnectionType_name = map[int32]string{
		0: "NOT_CONNECTED",
		1: "CONNECTED",
		2: "CAN_CONNECT",
		3: "CANNOT_CONNECT",
	}
	Message_ConnectionType_value = map[string]int32{
		"NOT_CONNECTED":  0,
		"CONNECTED":      1,
		"CAN_CONNECT":    2,
		"CANNOT_CONNECT": 3,
	}
)

func (x Message_ConnectionType) Enum() *Message_ConnectionType {
	p := new(Message_ConnectionType)
	*p = x
	return p
}

func (x Message_ConnectionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Message_ConnectionType) Descriptor() protoreflect.EnumDescriptor {
	return file_msg_proto_enumTypes[1].Descriptor()
}

func (Message_ConnectionType) Type() protoreflect.EnumType {
	return &file_msg_proto_enumTypes[1]
}

func (x Message_ConnectionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Message_ConnectionType.Descriptor instead.
func (Message_ConnectionType) EnumDescriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0, 1}
}

// Message is the top-level envelope for exchanging
// information with the DHT protocol.
type Message struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// defines what type of message it is.
	Type Message_MessageType `protobuf:"varint,1,opt,name=type,proto3,enum=zikade.dht.pb.Message_MessageType" json:"type,omitempty"`
	// defines what coral cluster level this query/response belongs to.
	// in case we want to implement coral's cluster rings in the future.
	//
	// Deprecated: Marked as deprecated in msg.proto.
	ClusterLevelRaw int32 `protobuf:"varint,10,opt,name=cluster_level_raw,json=clusterLevelRaw,proto3" json:"cluster_level_raw,omitempty"`
	// Used to specify the key associated with this message.
	// PUT_VALUE, GET_VALUE, ADD_PROVIDER, GET_PROVIDERS
	Key []byte `protobuf:"bytes,2,opt,name=key,proto3" json:"key,omitempty"`
	// Used to return a value
	// PUT_VALUE, GET_VALUE
	Record *pb.Record `protobuf:"bytes,3,opt,name=record,proto3" json:"record,omitempty"`
	// Used to return peers closer to a key in a query
	// GET_VALUE, GET_PROVIDERS, FIND_NODE
	CloserPeers []*Message_Peer `protobuf:"bytes,8,rep,name=closer_peers,json=closerPeers,proto3" json:"closer_peers,omitempty"`
	// Used to return Providers
	// GET_VALUE, ADD_PROVIDER, GET_PROVIDERS
	ProviderPeers []*Message_Peer `protobuf:"bytes,9,rep,name=provider_peers,json=providerPeers,proto3" json:"provider_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message) Reset() {
	*x = Message{}
	mi := &file_msg_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message) ProtoMessage() {}

func (x *Message) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message.ProtoReflect.Descriptor instead.
func (*Message) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0}
}

func (x *Message) GetType() Message_MessageType {
	if x != nil {
		return x.Type
	}
	return Message_PUT_VALUE
}

// Deprecated: Marked as deprecated in msg.proto.
func (x *Message) GetClusterLevelRaw() int32 {
	if x != nil {
		return x.ClusterLevelRaw
	}
	return 0
}

func (x *Message) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *Message) GetRecord() *pb.Record {
	if x != nil {
		return x.Record
	}
	return nil
}

func (x *Message) GetCloserPeers() []*Message_Peer {
	if x != nil {
		return x.CloserPeers
	}
	return nil
}

func (x *Message) GetProviderPeers() []*Message_Peer {
	if x != nil {
		return x.ProviderPeers
	}
	return nil
}

type Message_Peer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// ID of a given peer.
	Id []byte `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// multiaddrs for a given peer
	Addrs [][]byte `protobuf:"bytes,2,rep,name=addrs,proto3" json:"addrs,omitempty"`
	// used to signal the sender's connection capabilities to the peer
	Connection    Message_ConnectionType `protobuf:"varint,3,opt,name=connection,proto3,enum=zikade.dht.pb.Message_ConnectionType" json:"connection,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Message_Peer) Reset() {
	*x = Message_Peer{}
	mi := &file_msg_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Message_Peer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Message_Peer) ProtoMessage() {}

func (x *Message_Peer) ProtoReflect() protoreflect.Message {
	mi := &file_msg_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Message_Peer.ProtoReflect.Descriptor instead.
func (*Message_Peer) Descriptor() ([]byte, []int) {
	return file_msg_proto_rawDescGZIP(), []int{0, 0}
}

func (x *Message_Peer) GetId() []byte {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *Message_Peer) GetAddrs() [][]byte {
	if x != nil {
		return x.Addrs
	}
	return nil
}

func (x *Message_Peer) GetConnection() Message_ConnectionType {
	if x != nil {
		return x.Connection
	}
	return Message_NOT_CONNECTED
}

var File_msg_proto protoreflect.FileDescriptor

const file_msg_proto_rawDesc = "" +
	"\n" +
	"\tmsg.proto\x12\rzikade.dht.pb\x1a2github.com/libp2p/go-libp2p-record/pb/record.proto\"\xeb\x04\n" +
	"\aMessage\x126\n" +
	"\x04type\x18\x01 \x01(\x0e2\".zikade.dht.pb.Message.MessageTypeR\x04type\x12.\n" +
	"\x11cluster_level_raw\x18\n" +
	" \x01(\x05B\x02\x18\x01R\x0fclusterLevelRaw\x12\x10\n" +
	"\x03key\x18\x02 \x01(\fR\x03key\x12)\n" +
	"\x06record\x18\x03 \x01(\v2\x11.record.pb.RecordR\x06record\x12>\n" +
	"\fcloser_peers\x18\b \x03(\v2\x1b.zikade.dht.pb.Message.PeerR\vcloserPeers\x12B\n" +
	"\x0eprovider_peers\x18\t \x03(\v2\x1b.zikade.dht.pb.Message.PeerR\rproviderPeers\x1as\n" +
	"\x04Peer\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\fR\x02id\x12\x14\n" +
	"\x05addrs\x18\x02 \x03(\fR\x05addrs\x12E\n" +
	"\n" +
	"connection\x18\x03 \x01(\x0e2%.zikade.dht.pb.Message.ConnectionTypeR\n" +
	"connection\"i\n" +
	"\vMessageType\x12\r\n" +
	"\tPUT_VALUE\x10\x00\x12\r\n" +
	"\tGET_VALUE\x10\x01\x12\x10\n" +
	"\fADD_PROVIDER\x10\x02\x12\x11\n" +
	"\rGET_PROVIDERS\x10\x03\x12\r\n" +
	"\tFIND_NODE\x10\x04\x12\b\n" +
	"\x04PING\x10\x05\"W\n" +
	"\x0eConnectionType\x12\x11\n" +
	"\rNOT_CONNECTED\x10\x00\x12\r\n" +
	"\tCONNECTED\x10\x01\x12\x0f\n" +
	"\vCAN_CONNECT\x10\x02\x12\x12\n" +
	"\x0eCANNOT_CONNECT\x10\x03B\aZ\x05./;pbb\x06proto3"

var (
	file_msg_proto_rawDescOnce sync.Once
	file_msg_proto_rawDescData []byte
)

func file_msg_proto_rawDescGZIP() []byte {
	file_msg_proto_rawDescOnce.Do(func() {
		file_msg_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)))
	})
	return file_msg_proto_rawDescData
}

var file_msg_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_msg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_msg_proto_goTypes = []any{
	(Message_MessageType)(0),    // 0: zikade.dht.pb.Message.MessageType
	(Message_ConnectionType)(0), // 1: zikade.dht.pb.Message.ConnectionType
	(*Message)(nil),             // 2: zikade.dht.pb.Message
	(*Message_Peer)(nil),        // 3: zikade.dht.pb.Message.Peer
	(*pb.Record)(nil),           // 4: record.pb.Record
}
var file_msg_proto_depIdxs = []int32{
	0, // 0: zikade.dht.pb.Message.type:type_name -> zikade.dht.pb.Message.MessageType
	4, // 1: zikade.dht.pb.Message.record:type_name -> record.pb.Record
	3, // 2: zikade.dht.pb.Message.closer_peers:type_name -> zikade.dht.pb.Message.Peer
	3, // 3: zikade.dht.pb.Message.provider_peers:type_name -> zikade.dht.pb.Message.Peer
	1, // 4: zikade.dht.pb.Message.Peer.connection:type_name -> zikade.dht.pb.Message.ConnectionType
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_msg_proto_init() }
func file_msg_proto_init() {
	if File_msg_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_msg_proto_rawDesc), len(file_msg_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_msg_proto_goTypes,
		DependencyIndexes: file_msg_proto_depIdxs,
		EnumInfos:         file_msg_proto_enumTypes,
		MessageInfos:      file_msg_proto_msgTypes,
	}.Build()
	File_msg_proto = out.File
	file_msg_proto_goTypes = nil
	file_msg_proto_depIdxs = nil
}
